### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by shandlermason** [rohitgeddam/CSC510_PROJECT1#1]
1. Brainstorm ideas
2. Prepare 2 project ideas and tasks the team can do with the project
3. Come prepared to team meeting on August 26th at 8pm

**Comment by shandlermason** [comment]
Idea 1: 

- Single query feedback system: Students have multiple questions/queries and we can create a single system to answer all queries
- Type into query and question goes to the right person and the people receiving query can reply in same application
- For example, immunization question goes to health center using query web app 
- Small scope, just a few departments, project is expandable for other departments
- One stop shop for every NC State students question 
- Problem: cannot integrate into MyPack, we would need to create out own interface

Idea 2: 

- Create search engine/library with different fields
- Upon query, database will provide full syllabus and reading materials curated by professors for a specific course that was searched
-  Results will show chapter or topic wise a selection of materials

Idea 3: 

- Mobile app: app takes photo of raw foods (tomatoes, carrots) and app shows recipes you can make using the food

Idea 4: 

- Carpooling, uber-like for NC State 

Idea 5: 

- On campus food delivery, door dash for NC State 

Idea 6: 

- Roommate finder web app, app eases the process instead of trying to find a roommate using whats app
- Would be solving a real world problem, for NC State, scalability, 
- No good websites to find roommates
- App needs to be interactive, extendable
- Possibly using social media handles to match roommates by using analysis of social media posts

Idea 7: 

- Stock market clone game, mimic the stock market, give fake dollars to user
- Learn how to trade and invest using fake dollars

Idea 8: 

- Extending upon unit convertor extension (google chrome extension) 
- Equation convertor extension,
- Code convertor extension - convert python code to description of what its doing
- Built in option to snip part of screen and google will search it for you 

Idea 9: 

- Disability: one leg shorter than the other one, met someone else who had the same problem, not alone
- Create health care based app, people sign up and post disabilities so people can have a place to interact with people going through the same thing
- Be able to connect with another person similar to you, social app, focus on 1 disability, can have anonymous users
- Add zoom/video call API

**Meeting Proof**

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/46688470/187009207-fcebb147-33f1-4077-83f1-830ad7e710b2.png">

**Comment by shandlermason** [comment]
I vote idea 1 and idea 6

**Comment by rohitgeddam** [comment]
**I vote for Idea 1, 6**

**Comment by Darkviper7** [comment]
I vote for 1 and 6

**Comment by shandlermason** [comment]
Idea 6 is the winner!
